AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
  EnvType:
    Type: String
    AllowedValues:
      - prod
      - test
  Domain:
    Type: String
  SSLCertificate:
    Type: String
  MinContainers:
    Type: Number
  MaxContainers:
    Type: Number

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        EnvType: !Ref EnvType
      TemplateURL: stacks/vpc.yaml

  iam:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        EnvType: !Ref EnvType
      TemplateURL: stacks/iam.yaml

  app:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        EnvType: !Ref EnvType
        Domain: !Ref Domain
        OperatorsGroup: !GetAtt iam.Outputs.OperatorsGroup
        SSLCertificate: !Ref SSLCertificate
      TemplateURL: stacks/app.yaml

  api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        EnvType: !Ref EnvType
        Domain: !Ref Domain
        VPC: !GetAtt vpc.Outputs.VPC
        PublicSubnets: !GetAtt vpc.Outputs.PublicSubnets
        OperatorsGroup: !GetAtt iam.Outputs.OperatorsGroup
        SSLCertificate: !Ref SSLCertificate
        MinContainers: !Ref MinContainers
        MaxContainers: !Ref MaxContainers
      TemplateURL: stacks/api.yaml

Outputs:
  VPC:
    Value: !GetAtt vpc.Outputs.VPC
  PublicSubnets:
    Value: !GetAtt vpc.Outputs.PublicSubnets
  WebsiteURL:
    Value: !GetAtt app.Outputs.WebsiteURL
