AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Type: String
    Default: mipaquete
  Environment:
    Type: String
    Default: test
    AllowedValues:
    - prod
    - test
  Domain:
    Type: String
    Default: mipaquete.transadmin.co
Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        Environment:
          Ref: Environment
      TemplateURL: https://s3.amazonaws.com/transadmin.co-cf-templates/283d16bbe86cbc6e116e5af79eaede3e.template
Outputs:
  VPC:
    Value:
      Fn::GetAtt:
      - vpc
      - Outputs.VPC
  PublicSubnets:
    Value:
      Fn::GetAtt:
      - vpc
      - Outputs.PublicSubnets
