AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
  EnvType:
    Type: String
    AllowedValues:
      - prod
      - test
  Domain:
    Type: String
  SSLCertificate:
    Type: String
    Default: ""
  MinContainers:
    Type: Number
  MaxContainers:
    Type: Number

Conditions:
  IsProd: !Equals [!Ref EnvType, prod]

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Condition: IsProd
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
      TemplateURL: stacks/vpc.yaml

  elb:
    Type: AWS::CloudFormation::Stack
    Condition: IsProd
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt vpc.Outputs.VpcId
        SubnetIds: !GetAtt vpc.Outputs.SubnetIds
      TemplateURL: stacks/elb.yaml

  iam:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        EnvType: !Ref EnvType
      TemplateURL: stacks/iam.yaml

  app:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        EnvType: !Ref EnvType
        Domain: !Ref Domain
        OperatorsGroup: !GetAtt iam.Outputs.OperatorsGroup
        SSLCertificate: !Ref SSLCertificate
      TemplateURL: stacks/app.yaml

  api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        VpcId: !If
          - IsProd
          - !GetAtt vpc.Outputs.VpcId
          - Fn::ImportValue: !Join ["-", [!Ref ProjectName, vpc]]
        SubnetIds: !If
          - IsProd
          - !GetAtt vpc.Outputs.SubnetIds
          - Fn::ImportValue: !Join ["-", [!Ref ProjectName, subnets]]
        EnvType: !Ref EnvType
        Domain: !Ref Domain
        OperatorsGroup: !GetAtt iam.Outputs.OperatorsGroup
        SSLCertificate: !Ref SSLCertificate
        LoadBalancer: !If
          - IsProd
          - !GetAtt elb.Outputs.LoadBalancer
          - Fn::ImportValue: !Join ["-", [!Ref ProjectName, loadbalancer]]
        LoadBalancerSecurityGroup: !If
          - IsProd
          - !GetAtt elb.Outputs.LoadBalancerSecurityGroup
          - Fn::ImportValue: !Join ["-", [!Ref ProjectName, loadbalancer, sg]]
        ECSCluster: !If
          - IsProd
          - !GetAtt elb.Outputs.ECSCluster
          - Fn::ImportValue: !Join ["-", [!Ref ProjectName, ecs, cluster]]
        MinContainers: !Ref MinContainers
        MaxContainers: !Ref MaxContainers
      TemplateURL: stacks/api.yaml

Outputs:
  LoadBalancerURL:
    Value: !If
      - IsProd
      - !GetAtt elb.Outputs.LoadBalancerURL
      - Fn::ImportValue: !Join ["-", [!Ref ProjectName, loadbalancer, url]]
  WebsiteURL:
    Value: !GetAtt app.Outputs.WebsiteURL
  WebsiteDistributionId:
    Condition: IsProd
    Value: !GetAtt app.Outputs.DistributionId
