AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [!Ref ProjectName, loadbalancer]]
      GroupDescription: !Sub "SecurityGroup for ${ProjectName} LoadBalancer"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8443
          ToPort: 8443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref ProjectName, loadbalancer]]

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref ProjectName
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets: !Ref SubnetIds
      LoadBalancerAttributes:
        - Key: routing.http2.enabled
          Value: "false"
        - Key: deletion_protection.enabled
          Value: "false"
        - Key: idle_timeout.timeout_seconds
          Value: "60"
        - Key: access_logs.s3.enabled
          Value: "false"

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ["-", [!Ref ProjectName, cluster]]

Outputs:
  LoadBalancer:
    Value: !Ref LoadBalancer
    Export:
      Name: !Join ["-", [!Ref ProjectName, loadbalancer]]
  LoadBalancerURL:
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Join ["-", [!Ref ProjectName, loadbalancer, url]]
  LoadBalancerSecurityGroup:
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: !Join ["-", [!Ref ProjectName, loadbalancer, sg]]
  ECSCluster:
    Value: !Ref ECSCluster
    Export:
      Name: !Join ["-", [!Ref ProjectName, ecs, cluster]]
